services:
  pebble-relay:
    image: ghcr.io/hkgood/pebble-relay:main
    restart: always
    ports:
      - "8977:8977"
    volumes:
      - relay-data:/data
    environment:
      - PB_URL=${PB_URL:-https://pb.osglab.com}
      - PB_SUPERUSER_EMAIL=${PB_SUPERUSER_EMAIL:-rocky.hk@gmail.com}
      - PB_SUPERUSER_PASSWORD=${PB_SUPERUSER_PASSWORD:-gz203799}
      - RELAY_ADMIN_PASSWORD=${RELAY_ADMIN_PASSWORD:-pebblereply}

volumes:
  relay-data:
